//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yahtzee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFace
    {
        public int idLance { get; set; }
        public Nullable<int> nbLancee { get; set; }
        public Nullable<int> idDe { get; set; }
    
        public virtual tblDe tblDe { get; set; }
    }
}
